### PR TITLE
extended ADC functionality

### PR DESCRIPTION
**Pull request by p-h-a-i-l**
~some work needed..~
~Include guards not yet working for hoverboard mode.~

@btsimonh What do you think, should we take the time and put all the analog thresholds and multipliers into flash storage?

### CODE REVIEW

**Comment by juodumas** [comment]
Sharing what we have tried with ADC control:
1. Single ADC input sets same speed 0-1000 for both wheels. E.g. scooter with 1 motor wheel front & 1 back.
2. One ADC input sets speed 0-1000 for both wheels, another ADC sets steering coeficient.
3. Two ADCs control 2 wheels independently, setting speed from -1000 to +1000. E.g. a driving chair with 2 "joysticks".

Code for point 1:

```c
// adc_buffer.l_tx2 / adc_buffer.l_rx2 should be configurable:
if (adc_buffer.l_tx2 >= ADC_MIN) {
  cmd1 = CLAMP((adc_buffer.l_tx2 - ADC_MIN) * 1000 / (ADC_MAX - ADC_MIN), 0, 1000);
}
else {
  cmd1 = 0;
}

// We never reach speed 1000 due to filter, would be nice to fix.
speed = CLAMP(speed * (1.0 - FILTER) + cmd1 * FILTER, 0, 1000);

#ifdef INVERT_L_DIRECTION
pwms[0] = -speed;
#else
pwms[0] = speed;
#endif

#ifdef INVERT_R_DIRECTION
pwms[1] = speed;
#else
pwms[1] = -speed;
#endif
```

Point 2 is this PR.

Code for point 3:
```c
if (adc_buffer.l_tx2 < ADC1_MIN_HARD || adc_buffer.l_rx2 < ADC2_MIN_HARD || adc_buffer.l_tx2 > ADC1_MAX_HARD || adc_buffer.l_rx2 > ADC2_MAX_HARD) {
  cmd1 = 0;
  cmd2 = 0;
}
else {
  cmd1 = CLAMP(((adc_buffer.l_tx2 - ADC1_MID) * 1000) / ADC1_DIFF_HALF, -1000, 1000);
  cmd2 = CLAMP(((adc_buffer.l_rx2 - ADC2_MID) * 1000) / ADC2_DIFF_HALF, -1000, 1000);
  if (abs(cmd1) < 50) cmd1 = 0;
  if (abs(cmd2) < 50) cmd2 = 0;
}

speedR = CLAMP(speedR * (1.0 - FILTER) + cmd1 * FILTER, -1000, 1000);
speedL = CLAMP(speedL * (1.0 - FILTER) + cmd2 * FILTER, -1000, 1000);

#ifdef INVERT_L_DIRECTION
pwms[0] = -speed;
#else
pwms[0] = speed;
#endif

#ifdef INVERT_R_DIRECTION
pwms[1] = speed;
#else
pwms[1] = -speed;
#endif
```

**Comment by p-h-a-i-l** [comment]
>     1. Single ADC input sets same speed 0-1000 for both wheels. E.g. scooter with 1 motor wheel front & 1 back.

can be configured with the code in this PR
 
>     2. One ADC input sets speed 0-1000 for both wheels, another ADC sets steering coeficient.

can be configured with the code in this PR

>     3. Two ADCs control 2 wheels independently, setting speed from -1000 to +1000. E.g. a driving chair with 2 "joysticks".

I call it tank mode ;)
yeah, we should add that to cover all possible scenarios

**Comment by p-h-a-i-l** [comment]
nevermind, added tankmode ;)

code is getting ugly with all these defines..

**Comment by btsimonh** [comment]
I've never used ADC mode, but there are a couple of people here now who at least want to.
Might be nice to
1/ put constants in flash with meaningful defaults.
2/ make sure ADC mode is DISABLED by the force serial USART2 power button long press... :).  (see setUSART2ToControl() near end of setup.c) - and ensure that this is available in ADC mode.
(not sure if you noticed that; it's untested, but you can select serial onto USART2 with a low press on power button - the intent being that you could configure flash, etc. easily even in modes where USART2 was sensor/adc, etc.  Probably needs to be extended to DISABLE and additonal USART2 line use appropriately.  But if you are testing the ADC mode, pls could you test this long press functionality?).
3/ I would REALLY like to get to a single firmware which has all modes able to be enabled through flash - and bring ALL the defines into flash.  The flash is in a known position, so technically, as well as the 'force USART2 serial' for initial configuration, we could commit 'normal config images' and an explanation on how to put a flash config on through OCD?
Suggest we merge this, and have a small separate task of 'flashifying'?

**Comment by p-h-a-i-l** [comment]
> 2/ make sure ADC mode is DISABLED by the force serial USART2 power button long press... :). (see setUSART2ToControl() near end of setup.c) - and ensure that this is available in ADC mode.
> (not sure if you noticed that; it's untested, but you can select serial onto USART2 with a low press on power button - the intent being that you could configure flash, etc. easily even in modes where USART2 was sensor/adc, etc. Probably needs to be extended to DISABLE and additonal USART2 line use appropriately. But if you are testing the ADC mode, pls could you test this long press functionality?).

Oh, nice. I'll have a look. Well, it really needs to be disabled, since USART2 and our ADC pins share the same I/Os.  I hope this doesn't add too much complexity now.


> Suggest we merge this, and have a small separate task of 'flashifying'?

agreed

**Comment by p-h-a-i-l** [comment]
prepared for merging, not yet flashifyied.

Can someone check https://github.com/bipropellant/bipropellant-hoverboard-firmware/wiki/ADC-Configurations and see if is comprehensible?

Reactivated old timeout functionality until the shiny new system is in place.

**Comment by p-h-a-i-l** [comment]
@btsimonh unfortunately I didn't have time to test longpress mode yet..

**Comment by btsimonh** [comment]
> Can someone check https://github.com/bipropellant/bipropellant-hoverboard-firmware/wiki/ADC-Configurations and see if is comprehensible?

makes sense to me :).  Still hate all the defines....

**Pull request merged**
