### PR TITLE
Add C++ sample code for machine protocol and references

### PR DESCRIPTION
**Pull request by p-h-a-i-l**
code not tested yet. Does it look plausible?
If someone has a 3.3V arduino handy, please try :)

@btsimonh, do you think we should add sample code to the readme. I think this helps to get people hooked ;)
We could also move it to the wiki or examples folder..

### CODE REVIEW

**Comment by p-h-a-i-l** [comment]
- [ ] add information about ack and noack SOM to documentation

**Comment by AntumArk** [comment]
Not working well. Left wheel spins up for time to time. Right - no response.

**Comment by p-h-a-i-l** [comment]
how often are you sending the command?

**Comment by p-h-a-i-l** [comment]
and please try larger values for the second wheel:  `setHoverboardPWM(200,200); `

**Comment by p-h-a-i-l** [comment]
also corrected the typo reported by @atc1441

**Comment by AntumArk** [comment]
Tried sending full packet, got both wheels to turn but they are making really loud sound.

**Comment by AntumArk** [comment]
void setHoverboardPWM1( int32_t base_pwm, int32_t steer )
{
UART_Packet_t ups;
cc++;

ups.msgToHover.SOM = 4 ;
ups.msgToHover.CI = cc;
ups.msgToHover.len = 2 + 4 + 4;
ups.msgToHover.cmd = 'R';
ups.msgToHover.code = 0x0E;
ups.msgToHover.base_pwm1 = base_pwm;
ups.msgToHover.base_pwm2 = base_pwm >> 8;
ups.msgToHover.base_pwm3 = base_pwm >> 16;
ups.msgToHover.base_pwm4 = base_pwm >> 24;
ups.msgToHover.steer1 = steer;
ups.msgToHover.steer2 = steer >> 8;
ups.msgToHover.steer3 = steer >> 16;
ups.msgToHover.steer4 = steer >> 24;
ups.msgToHover.CS = 0;

for (int i = 0; i < ups.msgToHover.len; i++) {
ups.msgToHover.CS -= ups.UART_Packet[i + 1];
} 
This works.

**Comment by atc1441** [comment]
Oh yes I remember that is the code I used

If it is okay I could upload my code iam using with all the functions. That I made out of Hoverboard API as you can see in the last video I made with the timeout.  So including ACK and battery voltage etc.

But I don't know if this ok after the laws of GPL? As it is so hardly edited

**Comment by p-h-a-i-l** [comment]
> But I don't know if this ok after the laws of GPL? As it is so hardly edited

If your concerns are in regard to the hoverboardAPI you can go forward, no worries

**Comment by p-h-a-i-l** [comment]
> void setHoverboardPWM1( int32_t base_pwm, int32_t steer )
> {
> UART_Packet_t ups;
> cc++;
> 
> ups.msgToHover.SOM = 4 ;
> ups.msgToHover.CI = cc;
> ups.msgToHover.len = 2 + 4 + 4;
> ups.msgToHover.cmd = 'R';
> ups.msgToHover.code = 0x0E;
> ups.msgToHover.base_pwm1 = base_pwm;
> ups.msgToHover.base_pwm2 = base_pwm >> 8;
> ups.msgToHover.base_pwm3 = base_pwm >> 16;
> ups.msgToHover.base_pwm4 = base_pwm >> 24;
> ups.msgToHover.steer1 = steer;
> ups.msgToHover.steer2 = steer >> 8;
> ups.msgToHover.steer3 = steer >> 16;
> ups.msgToHover.steer4 = steer >> 24;
> ups.msgToHover.CS = 0;
> 
> for (int i = 0; i < ups.msgToHover.len; i++) {
> ups.msgToHover.CS -= ups.UART_Packet[i + 1];
> }
> This works.

Thanks! If you can give me the full .ino file, we can also add it to the example folder

**Comment by AntumArk** [comment]
[hover.txt](https://github.com/bipropellant/bipropellant-hoverboard-firmware/files/3345285/hover.txt)

**Comment by p-h-a-i-l** [comment]
> void setHoverboardPWM1( int32_t base_pwm, int32_t steer )
> {
> UART_Packet_t ups;
> cc++;
> 
> ups.msgToHover.SOM = 4 ;
> ups.msgToHover.CI = cc;
> ups.msgToHover.len = 2 + 4 + 4;
> ups.msgToHover.cmd = 'R';
> ups.msgToHover.code = 0x0E;
> ups.msgToHover.base_pwm1 = base_pwm;
> ups.msgToHover.base_pwm2 = base_pwm >> 8;
> ups.msgToHover.base_pwm3 = base_pwm >> 16;
> ups.msgToHover.base_pwm4 = base_pwm >> 24;
> ups.msgToHover.steer1 = steer;
> ups.msgToHover.steer2 = steer >> 8;
> ups.msgToHover.steer3 = steer >> 16;
> ups.msgToHover.steer4 = steer >> 24;
> ups.msgToHover.CS = 0;
> 
> for (int i = 0; i < ups.msgToHover.len; i++) {
> ups.msgToHover.CS -= ups.UART_Packet[i + 1];
> }
> This works.

Are you sure this is working? It shouldn't :)
`ups.msgToHover.cmd = 'R'; ` triggers a read, shouldn't write the payload.
also what are base_pwm1..4?
Also we transmit individual pwms now (one for each wheel). Better to rename from steer and speed as this is confusing.

**Comment by p-h-a-i-l** [comment]
> [hover.txt](https://github.com/bipropellant/bipropellant-hoverboard-firmware/files/3345285/hover.txt)

I was thinking of full arduino code, including loop() and setup()

**Comment by AntumArk** [comment]
> > void setHoverboardPWM1( int32_t base_pwm, int32_t steer )
> > {
> > UART_Packet_t ups;
> > cc++;
> > ups.msgToHover.SOM = 4 ;
> > ups.msgToHover.CI = cc;
> > ups.msgToHover.len = 2 + 4 + 4;
> > ups.msgToHover.cmd = 'R';
> > ups.msgToHover.code = 0x0E;
> > ups.msgToHover.base_pwm1 = base_pwm;
> > ups.msgToHover.base_pwm2 = base_pwm >> 8;
> > ups.msgToHover.base_pwm3 = base_pwm >> 16;
> > ups.msgToHover.base_pwm4 = base_pwm >> 24;
> > ups.msgToHover.steer1 = steer;
> > ups.msgToHover.steer2 = steer >> 8;
> > ups.msgToHover.steer3 = steer >> 16;
> > ups.msgToHover.steer4 = steer >> 24;
> > ups.msgToHover.CS = 0;
> > for (int i = 0; i < ups.msgToHover.len; i++) {
> > ups.msgToHover.CS -= ups.UART_Packet[i + 1];
> > }
> > This works.
> 
> Are you sure this is working? It shouldn't :)
> `ups.msgToHover.cmd = 'R'; ` triggers a read, shouldn't write the payload.
> also what are base_pwm1..4?
> Also we transmit individual pwms now (one for each wheel). Better to rename from steer and speed as this is confusing.

Those are individual bytes.  I will double check with R.

**Comment by AntumArk** [comment]
> > [hover.txt](https://github.com/bipropellant/bipropellant-hoverboard-firmware/files/3345285/hover.txt)
> 
> I was thinking of full arduino code, including loop() and setup()

Arduino code should be changed a little as I am using my "Blue pill" as both relay and transmitter on Serial2

**Comment by AntumArk** [comment]
> > > void setHoverboardPWM1( int32_t base_pwm, int32_t steer )
> > > {
> > > UART_Packet_t ups;
> > > cc++;
> > > ups.msgToHover.SOM = 4 ;
> > > ups.msgToHover.CI = cc;
> > > ups.msgToHover.len = 2 + 4 + 4;
> > > ups.msgToHover.cmd = 'R';
> > > ups.msgToHover.code = 0x0E;
> > > ups.msgToHover.base_pwm1 = base_pwm;
> > > ups.msgToHover.base_pwm2 = base_pwm >> 8;
> > > ups.msgToHover.base_pwm3 = base_pwm >> 16;
> > > ups.msgToHover.base_pwm4 = base_pwm >> 24;
> > > ups.msgToHover.steer1 = steer;
> > > ups.msgToHover.steer2 = steer >> 8;
> > > ups.msgToHover.steer3 = steer >> 16;
> > > ups.msgToHover.steer4 = steer >> 24;
> > > ups.msgToHover.CS = 0;
> > > for (int i = 0; i < ups.msgToHover.len; i++) {
> > > ups.msgToHover.CS -= ups.UART_Packet[i + 1];
> > > }
> > > This works.
> > 
> > 
> > Are you sure this is working? It shouldn't :)
> > `ups.msgToHover.cmd = 'R'; ` triggers a read, shouldn't write the payload.
> > also what are base_pwm1..4?
> > Also we transmit individual pwms now (one for each wheel). Better to rename from steer and speed as this is confusing.
> 
> Those are individual bytes. I will double check with R.

Yes, it should be small 'r'.  
[HoverSerialAdvanced - Copy.zip](https://github.com/bipropellant/bipropellant-hoverboard-firmware/files/3345344/HoverSerialAdvanced.-.Copy.zip)

**Comment by AntumArk** [comment]
Same code works with speed control if you change command to 3.

**Comment by p-h-a-i-l** [comment]
@AntumArk This does not compile here. Is this really code you tested?

**Comment by p-h-a-i-l** [comment]
also you where right with 4 bytes, we changed the data type at one point. The code in readme _should_ work now

**Comment by AntumArk** [comment]
> @AntumArk This does not compile here. Is this really code you tested?

Sorry, a typo at hover.ino : setHoverboardPWM1->setHoverboardPWM

**Comment by p-h-a-i-l** [comment]
> > @AntumArk This does not compile here. Is this really code you tested?
> 
> Sorry, a typo at hover.ino : setHoverboardPWM1->setHoverboardPWM

Ok, but is it tested then?

**Comment by AntumArk** [comment]
> > > @AntumArk This does not compile here. Is this really code you tested?
> > 
> > 
> > Sorry, a typo at hover.ino : setHoverboardPWM1->setHoverboardPWM
> 
> Ok, but is it tested then?

Yes

**Comment by p-h-a-i-l** [comment]
> also you where right with 4 bytes, we changed the data type at one point. The code in readme _should_ work now
> 
> (if not, please try to change from
> ` for (int i = 0; i < (2 + ups.msgToHover.len); i++){`
> to
> ` for (int i = 0; i < (ups.msgToHover.len); i++){`

would you mind testing that too? probably need to change as quoted..

**Comment by AntumArk** [comment]
Spins up the motors, stops and after 10 seconds spins up again. Tried both CS offsets.

**Comment by AntumArk** [comment]
changed datatypes to int32_t and now it works. Used CS loop  with +2.

**Comment by p-h-a-i-l** [comment]
ok, weird. `int` should be the same as `int32_t`. But I'll change the sample.
Thanks for testing

**Comment by atc1441** [comment]
Here is my code of the HoverboardAPI and Protocoll for Arduino IDE

https://github.com/atc1441/ArduinoHoverboardAPI

if i need to change something licensewise please tell me. :)

**Pull request merged**
