### PR TITLE
Separateprotocol

### PR DESCRIPTION
**Pull request by p-h-a-i-l**
independence of protocol from global variables

includes https://github.com/bipropellant/bipropellant-hoverboard-firmware/pull/27 and https://github.com/bipropellant/bipropellant-hoverboard-firmware/pull/25

### CODE REVIEW

**Comment by btsimonh** [comment]
I think time for a re-think based on what you and I learned from our first attempt.  I'll merge this into separateascii, and then we can both re-assess?

**Comment by btsimonh** [comment]
actually, no need to merge, this is based on separateascii, so the code base already exists in the repo as separateprotocol!

**Comment by btsimonh** [comment]
@p-h-a-i-l - pls. take a look at branches 'newseparateprotocol' (both repos).
This is quick transfer of yours & mine on top of the new main.  It builds fine , I have not tested, and I've not reviewed the available commands;  so have a look at the structure and see if the spirit is there.
I have gone a little further than you may like.  There are only functions and one variable (enable_immediate) shared, I think.
No hurry, have real work to do now :).

**Comment by p-h-a-i-l** [comment]
Thanks for transferring and reviving the protocol separation.

Removing all traces of data types and codes from the submodule almost eliminates the need for me to have a separate submodule.
Reusing the code is convenient and also reduces the risk for me to add additional bugs, but the main benefit of sharing code between sender and receiver is to have the same codes and structs on both sides.

I can understand that it can be annoying to work with a submodule and having to update multiple repos for one change. But I can see some benefits too: By forcing to update the submodule when changing structs or codes, it becomes immediately clear that the change is a breaking change. 
With the new dynamic population of params it is also possible to experiment with new and changed codes and data without fiddling in the submodule. When the function is mature, the code can be added permanently.

**Pull request closed without merging**
