### PR TITLE
► Improved controller: faster and better overall

### PR DESCRIPTION
**Pull request by EmanuelFeru**
- the controller is faster and more light in memory footprint
- motor control is now done intependenly for each motor LEFT and RIGHT using Reusable code generation setting in Simulink
- fixed bug when chaging direction fast

TODO: Code compiles and builds. However does not spin the wheel on my Denver hoverboard. The init melody does not play (same for previous commits).
@btsimonh Can you check on your board?

### CODE REVIEW

**Comment by lalalandrus** [comment]
the reason this build fails is that the platformio.ini is missing the following declarations due to the fact that config.h is being ignored when platformio is driving the build options

#define CTRL_TYP_SEL           
#define PHASE_ADV_ENA           
#define COMM_DEACV_HI        
#define COMM_ACV_LO

**Comment by EmanuelFeru** [comment]
@lalalandrus 

I see in platformio.ini the env_default beeing selected is generic, so it should use the settings from config.h

```
env_default = genericSTM32F103RC
;env_default = hoverboard
;env_default = control_softwareserial
;env_default = control_usart2
;env_default = control_usart3

[env:genericSTM32F103RC]
; Default environment, uses settings as specified in config.h
```

**Comment by btsimonh** [comment]
travis build some different envs, and also via makefile build (not entirely sure how it operates... did not do that bit - @p-h-a-i-l ?)...
Add the variables to ALL envs in platformio.ini, and commit - to see if it fixes the travis builds.

**Comment by btsimonh** [comment]
and the makefile builds fail because the makefile does not contain the relevant .c files?

**Comment by EmanuelFeru** [comment]
I just updated platformio.ini and makefile

**Comment by btsimonh** [comment]
typo in makefile :( :)

**Comment by btsimonh** [comment]
trailing \

**Comment by EmanuelFeru** [comment]
Where is the typo ? (which line)

**Comment by btsimonh** [comment]
image

add a trailing backslash :).

**Comment by btsimonh** [comment]
I'll try to give this a go today; need a moment off from big headache in main work :).

**Comment by EmanuelFeru** [comment]
That's ok, take your time. I fixed the typo

**Comment by AntumArk** [comment]
Control usart2 build failed for me. Errors:

_src\ascii_proto_funcs.c:29:10: fatal error: ascii_protocol.h: No such file or directory
In file included from src\bldc.c:7:0:
inc/bldc.h:8:17: error: unknown type name 'ELECTRICAL_PARAMS'
extern volatile ELECTRICAL_PARAMS electrical_measurements;
^~~~~~~~~~~~~~~~~
In file included from src\bldc.c:8:0:
inc/hallinterrupts.h:76:17: error: unknown type name 'HALL_DATA_STRUCT'
extern volatile HALL_DATA_STRUCT HallData[2];
^~~~~~~~~~~~~~~~
inc/hallinterrupts.h:146:17: error: unknown type name 'HALL_DATA_STRUCT'
extern volatile HALL_DATA_STRUCT HallData[2];
^~~~~~~~~~~~~~~~
src\bldc.c:27:10: error: unknown type name 'ELECTRICAL_PARAMS'
volatile ELECTRICAL_PARAMS electrical_measurements;
^~~~~~~~~~~~~~~~~
src\bldc.c: In function 'DMA1_Channel1_IRQHandler':
src\bldc.c:97:28: error: request for member 'batteryVoltage' in something not a structure or union
electrical_measurements.batteryVoltage = batteryVoltage;
^
src\bldc.c:115:26: error: request for member 'motors' in something not a structure or union
electrical_measurements.motors[0].dcAmps = dclAmps;
^
src\bldc.c:116:26: error: request for member 'motors' in something not a structure or union
electrical_measurements.motors[1].dcAmps = dcrAmps;
^
src\bldc.c:119:26: error: request for member 'motors' in something not a structure or union
electrical_measurements.motors[0].dcAmpsAvgAcc += ABS(adc_buffer.dcl - offsetdcl);
^
src\bldc.c:120:26: error: request for member 'motors' in something not a structure or union
electrical_measurements.motors[1].dcAmpsAvgAcc += ABS(adc_buffer.dcl - offsetdcl);
^
src\bldc.c:123:28: error: request for member 'motors' in something not a structure or union
electrical_measurements.motors[0].dcAmpsAvg = electrical_measurements.motors[0].dcAmpsAvgAcc*MOTOR_AMP_CONV_DC_AMP/1000;
^
src\bldc.c:123:74: error: request for member 'motors' in something not a structure or union
electrical_measurements.motors[0].dcAmpsAvg = electrical_measurements.motors[0].dcAmpsAvgAcc*MOTOR_AMP_CONV_DC_AMP/1000;
^
src\bldc.c:124:28: error: request for member 'motors' in something not a structure or union
electrical_measurements.motors[1].dcAmpsAvg = electrical_measurements.motors[1].dcAmpsAvgAcc*MOTOR_AMP_CONV_DC_AMP/1000;
^
src\bldc.c:124:74: error: request for member 'motors' in something not a structure or union
electrical_measurements.motors[1].dcAmpsAvg = electrical_measurements.motors[1].dcAmpsAvgAcc*MOTOR_AMP_CONV_DC_AMP/1000;
^
src\bldc.c:125:28: error: request for member 'motors' in something not a structure or union
electrical_measurements.motors[0].dcAmpsAvgAcc = 0;
^
src\bldc.c:126:28: error: request for member 'motors' in something not a structure or union
electrical_measurements.motors[1].dcAmpsAvgAcc = 0;
^
src\bldc.c:131:39: error: request for member 'dcCurLim' in something not a structure or union
if(dclAmps > electrical_measurements.dcCurLim || timeout > TIMEOUT || enable == 0) {
^
src\bldc.c:139:39: error: request for member 'dcCurLim' in something not a structure or union
if(dcrAmps > electrical_measurements.dcCurLim || timeout > TIMEOUT || enable == 0) {
^
src\bldc.c:146:26: error: request for member 'motors' in something not a structure or union
electrical_measurements.motors[0].r1 = adc_buffer.rl1 - offsetrl1;
^
src\bldc.c:147:26: error: request for member 'motors' in something not a structure or union
electrical_measurements.motors[0].r2 = adc_buffer.rl2 - offsetrl2;
^
src\bldc.c:148:26: error: request for member 'motors' in something not a structure or union
electrical_measurements.motors[0].q  = curl;
^
src\bldc.c:150:26: error: request for member 'motors' in something not a structure or union
electrical_measurements.motors[1].r1 = adc_buffer.rr1 - offsetrr1;
^
src\bldc.c:151:26: error: request for member 'motors' in something not a structure or union
electrical_measurements.motors[1].r2 = adc_buffer.rr2 - offsetrr2;
^
src\bldc.c:152:26: error: request for member 'motors' in something not a structure or union
electrical_measurements.motors[1].q  = 0;//curl;
^
*** [.pioenvs\control_usart2\src\ascii_proto_funcs.o] Error 1
*** [.pioenvs\control_usart2\src\bldc.o] Error 1_

**Comment by btsimonh** [comment]
@AntumArk - looks like your two repos are not synced.

**Comment by AntumArk** [comment]
> @AntumArk - looks like your two repos are not synced.

Build successful.

**Comment by AntumArk** [comment]
Posting a video to test. Works really well.
https://photos.app.goo.gl/HvLSg8gwGaqBrUtR7

**Comment by lalalandrus** [comment]
> Posting a video to test. Works really well.
> https://photos.app.goo.gl/HvLSg8gwGaqBrUtR7

what processor is your board using?

**Comment by AntumArk** [comment]
GD103

**Comment by lalalandrus** [comment]
:( the gd103 runs at a higher processor clock speed, this is more evidence that the stm103 controller isnt fast enough

**Comment by btsimonh** [comment]
@AntumArk - have you got serial?  if so, what is output of 'S\n' ?
this should give you some idea on the code times.....

**Comment by AntumArk** [comment]
Main loop interval_us 4999; lates 1, processing_us 240, interval by tick 4, bldc freq 16060, bldc_us 70

**Comment by btsimonh** [comment]
that is better than before, I think mine was bldc_us 100.  @EmanuelFeru - it should be ok on the STM32.
> bldc freq 16060
check if the counter that makes this is before or after the 'return' which makes it 8khz.  (i have a modified one maybe, where I moved it to after....).

**Comment by EmanuelFeru** [comment]
> Posting a video to test. Works really well.
> https://photos.app.goo.gl/HvLSg8gwGaqBrUtR7

Awsome! @AntumArk, did you try full speed? Above 800 duty cycle, the phase advance engages. That is when you need a boost.

**Comment by AntumArk** [comment]
No, I haven't. I will try it later, probably tomorrow. Now I have other things to do.

**Comment by EmanuelFeru** [comment]
> What other things should I test?
1. Maximum speed test and check of the Phase advance behavior
2. I am especially interested for dynamic tests with changing directions back-and-forth (needed for hoverboard mode where direction changes very often).
3. You could also try different control methods to see the behavior. In config.h (or platformi.ini depending on settings) change the parameter:
`
CTRL_TYP_SEL 3 // [-] Control method selection: 0 = Commutation , 1 = Pure Trapezoidal , 2 = Sinusoidal, 3 = Sinusoidal 3rd armonic (default)
`
I am interested here, if you can confirm the improvement in noise compared to the Commutation method.
4. Another test: at low-to-medium motor speed do a sudden stop of the motor, to check that there is no "funny" behavior. By stop, I mean external stop by physically stopping the motor (not by command) for short time.

5. If possible, I would like to check what is the limitation in terms of Maximum running frequency for the controller. To know how fast can it maximally run. 
For now, these are the main tests.

* One general note: From the controller I am outputing the real/measured speed. For the future maybe we can plot those in the serial @btsimonh @lalalandrus

**Comment by btsimonh** [comment]
first run.  I merged your stuff into my branch (it's a little hacked).
All looks good so far.  Need to put some screws back in before trying true HB mode :).  But tried ip and is modes, and all seems fine.

**Comment by btsimonh** [comment]
hoverboard mode with my merged version:
https://photos.app.goo.gl/eHUBaqu3F1iwaRHT6

**Comment by lalalandrus** [comment]
> hoverboard mode with my merged version:
> https://photos.app.goo.gl/eHUBaqu3F1iwaRHT6
Weird I always thought Simon was a guy.. 🤣
I will try implementing a filter and integration

**Comment by EmanuelFeru** [comment]
Haha... Me too
Is this with the new control? :)

**Comment by btsimonh** [comment]
new control?  not sure.
Holding the HB, and twisting, it still 'pops' at speed; i.e. no big change in the 'ticks'.  maybe better at low speed.  Thinking of logging PWM values to to memory for diagnosis.
funny, did not hear any ticks using ip or is.... 
*Question:* holding and twisting:  When *reducing* the angle, the speed definitely slows a LOT quicker than if you turn off drive.  Does this control Speed or Power?
e.g. if the demand is removed, angle goes from big -> 0, what do we want to happen, and why does the motor stop so quickly?  (is the current dumping into the FETs now hard driving to 'zero' (~15v)? )

**Comment by EmanuelFeru** [comment]
That is strange, it should slow down as before. I only control duty cycle open loop. So, no feedback. And when input is 0, all 3 phases pwms are set to 0 which will/should open all FETs.

**Comment by btsimonh** [comment]
but it does not *open* all fets.
'0' sets *equal* drive up and down....
that's part of the issue....  we can't have zero crossing driving hard to 15v and at the same time have 'no drive' to fets if we set zero.
It's like we need to control dead time?
p.s. it probably does slow down as before....  just observing that if we are expecting control of torque, we don't really have it....  we sort of have a combination of control of speed and power.....

**Comment by EmanuelFeru** [comment]
Yes. I also feel some resistive torque when I put potentiometers to 0. But that is the same with Niklas implementation too. So, I suspect some issue on the pwm side. Even if we send 0 on u,v,w phases the pwm is not really 0. That I did not understood why or if comes from the timers TIM1 and TIM8 used for pwm.

And yes, we do not have torque control. This is a synchronous motor. These type of motors spin synchronously  at constant input. That means it inherently tries to keep the same speed synchronously for a constant input. To make it torque control, we need to close a loop with a P or PI control on the phase current.
Since we do not have that, we can also mimic it by integrating the input. That is why I proposed to put an integral part on the angle.

**Comment by lalalandrus** [comment]
> Yes. I also feel some resistive torque when I put potentiometers to 0. But that is the same with Niklas implementation too. So, I suspect some issue on the pwm side. Even if we send 0 on u,v,w phases the pwm is not really 0. That I did not understood why or if comes from the timers TIM1 and TIM8 used for pwm.
> 
Both hi and lo of the get a are driven by a single channel of the timer. They are set as complimentary so they never short via the fets with adjustable dead time. As long as the board is on in this configuration we will never get a true zero without reconfiguring gpio. This could be dangerous.

**Comment by EmanuelFeru** [comment]
This is how the motors work with the code from my main branch
https://photos.google.com/photo/AF1QipPpP0_L9yCwp3cAd1A-FKthg11PrCfxIPYlMvS-

**Comment by lalalandrus** [comment]
> This is how the motors work with the code from my main branch
> https://photos.google.com/photo/AF1QipPpP0_L9yCwp3cAd1A-FKthg11PrCfxIPYlMvS-

Linky no worky

**Comment by EmanuelFeru** [comment]
Here you go (I could not make the link shareable on my phone)
https://photos.app.goo.gl/E38ZATYqnf8wf9tE6

**Comment by EmanuelFeru** [comment]
@lalalandrus I confirm, you are right. There is always pwm through the phases, I just check it with an oscilloscope. Only when "enable=0" so timers are stopped there is true 0 via the phases.
I still wonder why... I understand it is a single channel timer, with center aligned, But if set 0 to the timer it should output 0 all the time by not counting. Isn't it?

**Comment by lalalandrus** [comment]
@EmanuelFeru since the pwm is on the same channel but opposite polarity there will always be a FET driven

**Comment by btsimonh** [comment]
and this must be so for sinusoidal drive.
Some drive styles (where bemf is read) benefit from 'off' periods on phases.  Since we seem to have current pins from at least two phases plus overall current (by looking at the software only), I guess this is factored into the original hardware design - whether it was used in the original firmware or not who knows.

**Comment by btsimonh** [comment]
The repo is a bit of a mess at the moment; anyone mind if I try to clean it up and provide one or two branches for consideration, based on the brilliant work done here?

**Comment by EmanuelFeru** [comment]
I am ok with cleaning... Same functionality with less code lines is always better. Let us know when you have something.

**Comment by EmanuelFeru** [comment]
I just computed the theoretical speed that the hoverboard can reach with the current Phase Advance calibration.
```
r_whl          = 6.5 * 2.54 * 1e-2 / 2; % [m] Wheel radius. Diameter = 6.5 inch (1 inch = 2.54 cm)
n_mot_max      = 1250; % [rpm] Maximum motor speed measured at 100% DutyCycle (with current Phase Advance calibration)
v_kph          = n_mot_max * (pi/30) * r_whl * 3.6; % [kph] Conversion from rpm to kph
```
image
```
Result: v_kph = 38.9
````
(It can go higher with different Phase Advance calibration but for me this is sufficient)

**Comment by AntumArk** [comment]
I did test with speed control. 

Max speed looked the same as original firmware. Maxed out at 1k value. 

Sound levels stayed minimal.

Switching directions from max to 0 stops the motor almost immediately. And transitioning from positive to negative has a slight deadzone(around 30 mm/s). 

Acceleration could be faster for my application.

Haven't measured current as I haven't done parsing.

**Comment by btsimonh** [comment]
@AntumArk - join the conversation in the [issue](https://github.com/bipropellant/bipropellant-hoverboard-firmware/issues/32); there are repos listed there which are 'up to date' compared to this one.

Speed I think has a deliberate dead zone - in all firmwares to date, a PWM < ~30 is unreliable.  I'm still thinking about slow speed direct sinusoidal drive.... (down to zero, but with torque).

**Comment by btsimonh** [comment]
merged the other one :)

**Pull request closed without merging**
