### PR TITLE
Newseparateprotocol

### PR DESCRIPTION
**Pull request by btsimonh**
separates the two repos further, moving a lot of variables and functions into the main repo, leaving only low level protocol functions in the  protocol repo.
Draft because we need to check functions provided

### CODE REVIEW

**Comment by btsimonh** [comment]
@p-h-a-i-l - Maybe we should compromise on SOME common structures - the ones most likely to be used for control.
e.g. the simplest control structures for speed, position, etc.
Then the functions which operate on these in the main repo have a *choice* to copy data to/from the (now more stable) structures, so enabling changes in the main repo without affecting the subrepo?
If you came up with the set you actually use in your ESP32 code, we could discuss?
I think what I'm saying is that these structures are what is used on the protocol, but are ALWAYS copied from/to rather than being used direct in the main repo.  one example I'm thinking of is 'electrical measurements' - I added a few bits for internal tracking, but that then affected the other repo, when the new values actually didn't even need to be exposed.

**Comment by p-h-a-i-l** [comment]
> @p-h-a-i-l - Maybe we should compromise on SOME common structures - the ones most likely to be used for control.

for sure, but first I'd like to fully understand your concern ;)

> I think what I'm saying is that these structures are what is used on the protocol, but are ALWAYS copied from/to rather than being used direct in the main repo. one example I'm thinking of is 'electrical measurements' - I added a few bits for internal tracking, but that then affected the other repo, when the new values actually didn't even need to be exposed.

I don't completely understand yet. 
If you change a small thing to the electrical measurements struct, it would be a breaking change which would indeed affect everyone using that.

**Comment by btsimonh** [comment]
example:
e.g. updated separateprotocol branch...

```
        int dcAmpsx100;

         int pwm_limiter;
        int pwm_requested;
        int pwm_actual;

         unsigned int limiter_count;
```
I should not have added these to that structure if that structure is used in protocol :).

So..  what I'm saying is we have Separate structures for common, stable 'interfaces', which are defined in the protocol repo.  We try to NOT change these. To encourage that, always have functions which copy to/from them, and maybe name the structure in the protocol repo 'PUBLIC_ELECTRICAL_MEASUREMENTS' and in the main repo 'PRIVATE_ELECTRICAL_MEASUREMENTS'.

Then arses like me won't change them for diagnostic purposes :).

But all functions should be in main repo except those servicing actual protocol related structures (e.g. protocol stats)?

**Comment by p-h-a-i-l** [comment]
I wouldn't rename all structs to PRIVATE_ in the protocol repo, that seems to blow up the names. But when overwritten in main repo, adding _PRIVATE makes sense.

Yes, all functions, which are not protocol related should be moved to the main repo.

**Comment by p-h-a-i-l** [comment]
Also had a look at the initialparams array, I only see 0x01, "sensor data" which could be moved to private from my point of view.

**Comment by btsimonh** [comment]
pls take a look at
https://github.com/btsimonh/bipropellant-protocol/tree/separateprotocol2
https://github.com/btsimonh/hoverboard-firmware/tree/separateprotocol2

> I wouldn't rename all structs to PRIVATE_ in the protocol repo, that seems to blow up the names. But when overwritten in main repo, adding _PRIVATE makes sense.

agree, but not in above, i renamed the ones in protocol, not in main.  but easy enough to do reverse.
Only first 2/3 functions modified at the moment; but it gives a flavour of the intent.  let me know if this is the right direction....

**Comment by p-h-a-i-l** [comment]
didn't mean to push to this remote, but since it's there now: have a look at https://github.com/bipropellant/bipropellant-protocol/tree/separateprotocol

I want the functions out of the protocol, but dummy entries in initialparams. Otherwise there might be a mixup with  Codes. Since we only use dummystorage (contentbuf) we have no more dependencies back and can remove the ifdefs.

Also setParamVariable would fail all the time when trying to update variables from protocolfunctions.c.

I like the namespacing with PROTOCOL_ this is a clear indication that it affects others, too.

Why do you duplicate all structs? Isn't that kind of dangerous? Some kind of check if is still the same would be good..

I like the separation of the private protocol header.

**Comment by btsimonh** [comment]
> Why do you duplicate all structs? Isn't that kind of dangerous? Some kind of check if is still the same would be good.

a bit scary.  I don't know of a way to say 'are there two separately defined structures the same' to cause a compile error.  Maybe we just use #define POSN PROTOCOL_POSN - which may make someone think twice?

**Comment by p-h-a-i-l** [comment]
or use PROTOCOL_POSN directly. The PROTOCOL_ should make you think twice already :)

**Comment by btsimonh** [comment]
pls take a look at
https://github.com/btsimonh/bipropellant-protocol/tree/separateprotocol2
https://github.com/btsimonh/hoverboard-firmware/tree/separateprotocol2
(Again).
if we go with these, a quick test, then get them into master?

**Comment by p-h-a-i-l** [comment]
machine protocol is working, will merge as soon as I tested ASCII mode

**Comment by p-h-a-i-l** [comment]
ASCII protocol working! merging..

**Comment by btsimonh** [comment]
merge the wrong way?

**Comment by p-h-a-i-l** [comment]
no, needed to resolve a conflict first. Waiting for travis now

**Comment by btsimonh** [comment]
yeah!  huge branch cull! (hope i did not delete anyone elses....)

**Comment by p-h-a-i-l** [comment]
I'm pretty sure, that I did the branch massacre in this repo ;)

**Comment by btsimonh** [comment]
sourcetree does not tell me if is ACTUALLY deletes from remote (i.e. if the branch still exists), but i have to delete from the interface as it seems to keep all the remote branches local until you do :).

**Pull request merged**
